### ISSUE TITLE
FED - Internet Explorer - Larger and wider covers are being cut off

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#62]
see attached image
![1_cut off covers](https://cloud.githubusercontent.com/assets/7650441/8559176/d9edb054-24d7-11e5-890b-5294fb1687a5.jpg)

**Comment by Svalts** [comment]
Fixed on dev.

http://dev.fivemile.com.au/catalog/new-releases-0

Also, some images have different widths and heights so when is uploaded to drupal this will be an issue in some of the items.

**Comment by janetgatsby** [comment]
From Simon: Reduced the covers size, Internet explorer is hard to work with most of the time but I was able to figure it out.  (20 mins).

**Comment by janetgatsby** [comment]
@patpluspun does this need to be deployed?

**Comment by patpluspun** [comment]
it will be.  It's going into the release.

**Comment by janetgatsby** [comment]
@Svalts @patpluspun 
Guys, this is not fixed on production. Look in IE and I also see it on FF/Mac on the Children's Picture Books page: http://www.fivemile.com.au/catalog/children/picture-books

Decorating Disaster in first row (under featured) is still being cut off.
Fish Jam in third row (under featured) is still being cut off.

Did fix not get deployed or is there still a FED issue that needs resolve?

**Comment by Svalts** [comment]
@janetgatsby 

Regarding this issue, after some research <td> columns on CSS are not rendered with Internet Explorer nor this one ignores the width CSS property. Another way should be done. I can do it if you like. Let me know.

**Comment by janetgatsby** [comment]
@Svalts yes, please fix for the next milestone.

**Comment by janetgatsby** [comment]
I wish we had a "ready for deployment" state. Please add this to the next deployment.

**Comment by patpluspun** [comment]
@janetgatsby I only spent a scrap of time at this, but here is how the github api works: https://developer.github.com/v3/issues/

It appears that the issue state is locked to either `open` or `closed`, but the labels option can accept any arbitrary text and color.  I can look into adding a git hook that updates the label on a referenced issue to a green color and "ready for deployment" text.  It would add an extra label onto the issue for easier sorting.

**Comment by janetgatsby** [comment]
It's cool to leave it be, I was just venting, I have too many spreadsheets :)
